hyperium/http-body

Cargo.toml

The default set of features includes utilities.

Depend on only the `BufStream` trait.

---

src/lib.rs
tests/is_end_stream.rs

The previous default could report the stream was ended even though there may have been pending `trailers`.

Make default is_end_stream pessimistically return false

---

src/size_hint.rs

Firstly, I just removed a unused field and associated comments that were kind of in the way.  If there is further merit to that, then I suggest it be added in complete form when its ready.
Then, from my own first use, and hyper master branch usage, it would appear that the _exact_ form of SizeHint is the common case, so add a dedicated constructor for that case, reducing use to a simple one liner.

Add SizeHint::with_exact

---

src/lib.rs
src/next.rs

Adds trivial futures that return next data chunk and trailers.
Basically it is convenience for users so that they wouldn't need to wrap `next_*` into future object themself.
Since it takes reference, it is forced to have `Unpin` requirement, guess it is sad

Add Next futures conveniences

---

src/lib.rs
src/next.rs

I find this name a little clearer, and it also fixes a conflict if something implements both `Body` and `Stream`.

Rename the 'next' combinator to 'data'

---

src/lib.rs

See https://github.com/hyperium/hyper/issues/2067

implement Body for http::{Request, Response}

---

CHANGELOG.md
src/empty.rs
src/lib.rs

`Empty` is a little utility type that I have found useful in a few
scenarios. For example to make a "catch all" `tower::Service` that
always returns `404 Not Found` with an empty body.

Add `Empty`

---

Cargo.toml
src/full.rs
src/lib.rs

This implements a part of hyperium/hyper#2345.
This implements `Clone` and, for example, a client can clone it to retry requests (e.g. for [redirections][tower-http-79]).
[tower-http-79]: https://github.com/tower-rs/tower-http/pull/79

Add `Full`

---

CHANGELOG.md
src/empty.rs

I noticed this while working on https://github.com/hyperium/tonic/pull/622 as it broke some interop tests.

Correctly override `size_hint` and `is_end_stream` for `Empty`

---

CHANGELOG.md
src/combinators/box_body.rs

This makes `BoxBody` usable with [`RequireAuthorization`] which requires `ResBody: Default`.
[`RequireAuthorization`]: https://docs.rs/tower-http/0.1.1/tower_http/auth/struct.RequireAuthorization.html

Implement `Default` for `BoxBody`

---

src/lib.rs

Closes #57
This PR adds a `impl Body for String` to allow users to provide more ergonomic APIs that can support simple use case like passing a string. This PR does not add support for `&str` or `Cow<'a, str>` since neither of these pass an owned and thus mutable "buffer" view that can be used to track if we've returned the data in `poll_data` already.
cc @nmoutschen

Add String impl for body

---

src/lib.rs
src/limited.rs

This should be compared to the implementation in #60.

feat: add `Limited` body

---

CHANGELOG.md
Cargo.toml
src/lib.rs

- Add `String` impl for `Body`.
- Add `Limited` body implementation.

chore: Prepare `0.4.5` release

---

http-body-util/src/collected.rs
http-body-util/src/combinators/collect.rs
http-body-util/src/lib.rs

I noticed in some hyper tests if the body wasn't available immediately, some data was being lost. Eventually noticed it's because the buf list wasn't persisted between polls 🙃

http-body-util: fix Collect if a poll is not ready immediately

---

http-body-util/src/collected.rs
http-body/src/frame.rs

This new return type allows for a more ergonomic type conversion experience than the current "check-and-unwrap` flow the current return type encourages.
Fixes #77

Change return type of Frame::into_* methods from Option<T> to Result<T, Self>

---

http-body-util/Cargo.toml

This should potentially be a stricter range, since futures-util doesn't follow semver, but I'm leaving this at the most permissive thing that doesn't currently result in broken builds, since I don't know this project's stance on dependency versioning.
Fixes: #83

util: Fix futures-util allowed version range.

---

http-body/src/frame.rs

When trying to port tower-http to http-body 1.0 I ran into this
```rust
impl<B> Body for CompressionBody<B>
where
B: Body,
B::Error: Into<BoxError>,
{
type Data = Bytes;
type Error = BoxError;
fn poll_frame(
self: Pin<&mut Self>,
cx: &mut Context<'_>,
) -> Poll<Option<Result<Frame<Self::Data>, Self::Error>>> {
match self.project().inner.project() {
BodyInnerProj::Identity { inner } => {
// `inner` is a body that we need to poll and copy the
// bytes to a `Bytes`
let frame = match ready!(inner.poll_frame(cx)) {
Some(Ok(frame)) => frame,
Some(Err(err)) => return Poll::Ready(Some(Err(err.into()))),
None => return Poll::Ready(None),
};
let frame = match frame.into_data() {
Ok(buf) => {
let bytes = buf.copy_to_bytes(buf.remaining());
return Poll::Ready(Some(Ok(Frame::data(bytes))));
} …
```

Add `Frame::map_data`

---

http-body-util/src/lib.rs
http-body-util/src/stream.rs

This PR adds a `BodyStream` type to create a `Stream` from a `Body`. This is useful when you want to stream data from a `Body` to code that accepts a `Stream`.

Add BodyStream.

---

http-body-util/Cargo.toml
http-body-util/src/combinators/collect.rs
http-body-util/src/combinators/with_trailers.rs
http-body-util/src/stream.rs

As `futures-util` is used only in the test, `http-body-util` seems to be able to use `futures-core` instead of `futures-util` in the dependencies.

util: replace futures-util with futures-core

---

http-body-util/src/util.rs

This allows short-circuiting when there is a non-empty chunk.

perf(util): optimize `<BufList as Buf>::has_remaining`

---

http-body-util/src/util.rs

Using `take(len)` costs a bit in performance. If copying the full thing (which is what `Collected::to_bytes()` does), we can skip using `take(n)` and see a significant speed up.
Using hyper's body benchmarks, on my tiny VM, the perf improvement is from 5GB/s to 31GB/s.

perf: improve BufList::copy_to_bytes if len == remaining

---

http-body/src/size_hint.rs

Replaces deprecated `std::u64` with the corresponding primitive type.
https://doc.rust-lang.org/std/u64/index.html

refactor: replace deprecated std::u64 with primitive type

---

http-body-util/Cargo.toml
http-body-util/src/combinators/collect.rs
http-body-util/src/combinators/with_trailers.rs
http-body-util/src/lib.rs
http-body-util/src/stream.rs

feat(util): add BodyDataStream

---

.github/workflows/CI.yml

Applies some small refactoring.

refactor(ci): small refactoring

---

http-body-util/Cargo.toml
http-body-util/src/combinators/box_body.rs
http-body-util/src/combinators/frame.rs

It claimed `UnsyncBoxBody::new` creates a `BoxBody`. Not the end of the world, but still!

http-body-util: minor doc and lint fixes, raising msrv to 1.56

---

.github/workflows/CI.yml

This is similar to our other repos, that way we can set branch protections to just care about "CI is green", and new jobs can be added in this file only.

ci: make a final ci-is-green job

---

http-body-util/Cargo.toml
http-body-util/src/combinators/collect.rs
http-body-util/src/combinators/with_trailers.rs
http-body-util/src/stream.rs

No need to depend on the bigger crate.
While most crates using this (in combination with hyper and/or tower) are likely still going to depend on `futures-util` for a long time anyways, this potentially improves build pipelining a little bit, allowing the two util crates to be built in parallel.

Replace futures-util with futures-core in non-test code

---

http-body-util/Cargo.toml

Proposes to update `http-body-util`'s MSRV to 1.61 to use https://github.com/rust-lang/rust/pull/93827/.

chore(util): update msrv to 1.61

---

http-body-util/src/empty.rs

Allows `Empty`'s constructor in const context. Depends on #128.

feat(util): allow Empty constructor in const context

---

http-body/Cargo.toml

this commit updates the MSRV of the `http-body` crate to 1.61.
this brings the `http-body` crate into step with the MSRV of the `http-body-util` crate.
in #128, the MSRV of the `http-body-util` crate was update to 1.61. however, compiling a crate in practice requires being able to parse all of the package manifests in its workspace. this means that using more recent features, like `dep:` syntax for optional dependencies included via cargo features, will not work due to the older `1.49` toolchain supported by `http-body`.
see the rust reference, here:
<https://doc.rust-lang.org/cargo/reference/features.html#optional-dependencies>
see #140, which depends on this commit.

chore(http-body): update msrv to 1.61

---

http-body/src/lib.rs

this commit introduces some additional documentation for `Body::poll_frame(..)`.
this adds some explicit information about what different return values indicate, and how callers are expected to respond to particular outcomes. these docs are modeled after the equivalent sections in the documentation of [`Stream`](https://docs.rs/futures-core/0.3.31/futures_core/stream/trait.Stream.html#return-value) and [`Future`](https://doc.rust-lang.org/stable/std/future/trait.Future.html#return-value).

docs: notes on poll_frame return values

---

http-body-util/src/channel.rs

pr #140 introduced a new channel-backed body. this body provides an equivalent to the defunct `hyper::Body::channel()` interface that was exposed in hyper 0.14, and removed in the 1.0 major release.
the previous `Sender` type also included a useful method, `try_send_data()`, which allows a thread to _synchronously_ attempt to send data _outside_ of an asynchronous context.
<https://docs.rs/hyper/0.14.31/hyper/body/struct.Sender.html#method.try_send_data>
this commit introduces a loosely equivalent `Sender::try_send()` method to provide users of `http-body-util` with a means to send `Frame<T>` values outside of an asynchronous context, without potentially scheduling the caller to be woken later or yielding should the channel be full.
this function accepts a `Frame<D>` rather than a chunk …

feat(util): introduce `channel::Sender::try_send()`

---

http-body-util/src/channel.rs

this commit introduces two methods allowing callers to inspect the capacity, both available and maximum, of the channel-backed body.
this allows callers to observe when the channel is full.
X-Ref: #140

feat(util): introduce `Sender::{capacity, max_capacity}`

---

http-body-util/src/full.rs

fixes https://github.com/hyperium/http-body/issues/154.
this commit introduces a `http_body_util::Full::into_inner()` method.
this allows callers to consume a `Full<D>`, and reacquire the wrapped value. this matches the style of [many interfaces][into-inner-docs] offered by various types provided in `core` and `std` such as `Box<T>`, `Arc<T>`, `Mutex<T>`, as well as [many interfaces][tokio-into-inner-docs] offered by various types in `tokio` such as `BufWriter<T>`, `OnceCell<T>`, and so forth.
this pattern is also mirrored in other `http_body_util` types including `Either<L, R>`.
```rust
use http_body_util::Full;
const DATA: &[u8] = b"hello";
let full = Full::new(DATA);
assert_eq!(full.into_inner(), Some("hello").map(str::as_bytes));
```
NB: an `Full::inner()` method is not provided here. …

feat(util/full): introduce `Full::into_inner()`

---

http-body/src/size_hint.rs

This was useful to implement for a DoubleBody implementation, it's low complexity and seemingly only has one logical implementation so I made a quick PR for it

Implement perfect addition of two `SizeHint`'s
